?morley
data(morley)
names(morley)
data(morley)
summary(morley$Speed,na.rm = TRUE)
summary(morley)
View(morley)
?mtcars
view(mtcars)
amostraA = with(morley, sample(20,replace=F))
summary(amostraA)
summary(amostraA$Speed,na.rm = TRUE)
sort(amorstraA)
data(mtcars)
view(mtcars)
summary(mtcars$mpg,na.rm = TRUE)
summary(mtcars$disp,na.rm = TRUE)
summary(mtcars$hp,na.rm = TRUE)
summary(mtcars$drat,na.rm = TRUE)
summary(mtcars$wt,na.rm = TRUE)
summary(mtcars$qsec,na.rm = TRUE)
